### ISSUE TITLE
Change Image Selection on Quest?

### ISSUE THREAD

**Issue by jescriba** [codepath-jjc/LevelUpApp#67]
Should the quest image selection be more like the milestone/edit quest page?
![image](https://cloud.githubusercontent.com/assets/3940193/20868623/b4d9b988-ba14-11e6-85ee-71eb1b214da1.png)

vs currently
![image](https://cloud.githubusercontent.com/assets/3940193/20868625/c0d22590-ba14-11e6-89e3-78645f7478bc.png)

I kinda prefer the first. Thoughts? @jasonify @claudiuandrei

**Comment by jasonify** [comment]
I don't know if it makes a big difference so if it's just a visual thing let's leave it as is for now until Tuesday / Wednesday.

Though, a better idea might be to have a set of like 6 icons (star, triangle, etc) and just choose one randomly for the user (hopefully that hasnt been used before)?


That way we dont have the stupid problem with loading the quest either. It doesn't seem the image is as important for quests anyway.

**Comment by jescriba** [comment]
I made a custom view for that selectable image thing. So should be quick either way
